### ISSUE TITLE
NodOn soft remote only responds after second time button pushed

### ISSUE THREAD

**Issue by yemoH** [caseda/com.nodon#10] opened 2018-11-12 20:17 UTC
I use a NodOn soft remote to start a flow which turns off the lights. 

Problem: When I pull a button once, the blue led lights up once, but no action from Homey. When a few seconds later I push the same button again, only the blue lights up once, and the correct flow is executed. I have the feeling that this started since late September 2018.

Some of the things I tested / observed over the last week:
- Sometimes the led on the soft remote lights up once as green after I push the button a second time.
- When I check 'Athom Developer' it indicates the Z-wave route is directly to Homey, but is 'offline'. 
- Other z-wave devices are working as expected. (3 Fibaro wall plugs and 1 Multisensor 6)
- When I restart the NodOn app (v2.01) in Homey, the soft remote responds correctly after I push the button the first time. 
- Homey has version 1.5.12

**Comment by caseda** [comment] 2018-11-12 20:41
blue led = the signal was send, but homey did not respond (in time) with an "i received your signal" message.
green led = signal was send, and homey responded with the "i received your signal".

- what is the distance to homey? (taking walls and floors into consideration)
- what is the distance to the nearest plug? (taking walls and floors into consideration)
- has anything changed in the meanwhile? like the placement (does it change often?), or anything in the vicinity (metal objects can absorb z-wave signals)
3 wall plugs isn't a lot for a strong mesh around an entire house, especially if you keep moving the remote.
- what is the battery level? not just in the app (this van be wrong), more as in how long is the battery already inside the remote, you can check the battery level also on the remote itself (check the manual).
A low battery lowers the range big time, but also the placement of the remote can lower the range (which isn't big for z-wave anyway).

The "offline" is because it is a battery device, which is asleep unless you press a button (if you press a button you will see it come online in the developer tools, and offline again within 10 seconds).

**Comment by yemoH** [comment] 2018-11-13 19:03
Thank you for your quick reply and explanation of the difference between the blue and green led response. 
- The distance between Homey and NodOn soft remote is about 10ft / 3m with line of sight (no floor, no wall, no curtain, no metals)
- The distance to the nearest plug is also about 10ft / 3m. The plug is behind a couch. 
- I don't recall I changed anything. Both Homey and the remote are at the same location. 
- When I checked the battery level according to the manual it indicates with the highest level (>50%)

Tonight before I wanted to send you this message I decided to give it one more try. For me embarrassing, the remote worked as it should. Over the coming days I will check the remote a few more times. I will get back to you in a few days, probably on Saturday. 

Thank you for your help.

**Comment by yemoH** [comment] 2018-12-19 19:32
Sorry for the delay. During the last weeks, the NodOn remote only activates a flow on Homey after I pust a button a second time. I'm certainly not an expert but it looks to me the remote is in a kind of sleep mode. When I push a button twice, with a few seconds in between, the flow is activated. After that the remote works as expected. During all of this I'm standing at the same distance to Homey.

**Comment by caseda** [comment] 2019-05-04 18:23
As this is not an app issue, nothing i can do about range/sleeping issues of a device itself i will close this issue.
i don't have the issue at all myself so can't reproduce.

**Closed by caseda** 2019-05-04 18:23 UTC
